services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:0Eh7WvKyZA3qBRaSiLLwPfke6YueS061XkF/V1i2rq4=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ms_laravel_db
      DB_USERNAME: ms_demo_user
      DB_PASSWORD: securepassword
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_storage:/var/www/html/storage

  db:
    image: postgres:16-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_laravel_db
      POSTGRES_USER: ms_demo_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ms_demo_user -d ms_laravel_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data:
  app_storage: